version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: Password99!
      ACCEPT_EULA: Y
    ports:
      - "54321:1433"
    networks:
      - app-network
    volumes:
      - db-data:/var/opt/mssql
networks:
  app-network:
    driver: bridge

volumes:
  db-data:
